export const CREATE_TODO_POPUP_OPEN = "CREATE_TODO_POPUP_OPEN"
export const CREATE_TODO_POPUP_CLOSE = "CREATE_TODO_POPUP_CLOSE"

export const NEW_TODO_TITLE = "NEW_TODO_TITLE"
export const NEW_TODO_CONTENT = "NEW_TODO_CONTENT"
export const CREATE_NEW_TODO = "CREATE_NEW_TODO"
export const SET_NEW_TODO_LIST = "SET_NEW_TODO_LIST"
export const REMOVE_TODO = "REMOVE_TODO"
